[tox]
envlist = py314, py313, py312
isolated_build = True

[testenv]
deps =
    pytest
    pytest-cov
    pytest-qt
    pytest-mock
    hypothesis
    types-requests
    types-boto3
commands =
    pytest
